---
R1:
  hostname: '10.120.10.11'
  groups:
    - vios
R2:
  hostname: '10.120.10.12'
  groups:
    - vios
R3:
  hostname: '10.120.11.13'
  groups:
    - vios
R4:
  hostname: '10.120.12.14'
  groups:
    - vios
R5:
  hostname: '10.120.15.15'
  groups:
    - vios
# R6:
#   hostname: '10.121.1.66'
#   groups:
#     - vios
